### ISSUE TITLE
Bot is sometimes closing unexpectly.

### ISSUE THREAD

**Issue by Philaeux** [FroggedTV/grenouillebot#4]
- [x] Sometimes because of the calendar crawler
- [ ] Sometimes because of the IRC bot

**Comment by Philaeux** [comment]
Seems to be every day -_-

**Comment by ThibaultVlacich** [comment]
If I remember well @Pyrobolser had the same kind of problem. I think the IRC server is kicking the bot after inactivity.

**Comment by Philaeux** [comment]
There is no event firing from the IRC lib (no _on_disconnect and _on_kick) so i'm a bit confused. Even in debug, there is no special note coming from the bot. I will investigate, this should be something specific with the Twitch IRC server.

**Comment by Philaeux** [comment]
I think i found the event in the [Twitch Irc doc](https://github.com/justintv/Twitch-API/blob/master/IRC.md#reconnect), I just have to listen to it now...
